import { PlayerController } from "./player/controller.js";

const escapeHTML = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const sourceRow = (source) => `<li><b>${escapeHTML(source.provider)}</b> · ${escapeHTML(source.type)} · ${escapeHTML(source.quality)}<br><code>${escapeHTML(source.url)}</code> <span class="tag ${source.is_playable ? "" : "gold"}">${source.is_playable ? "reproduzível" : escapeHTML(source.validation || "recusada")}</span></li>`;

function layout(title, body) {
  document.querySelector("#app").innerHTML = `<main class="diagnostic-page"><a class="logo" href="/"><span class="logo-ring">&lt;/&gt;</span><span class="logo-name">craft<em>play</em></span></a><h1>${title}</h1>${body}</main>`;
}

export function initSpecialPage(api) {
  if (location.pathname === "/debug/providers") { initDebug(api); return true; }
  if (location.pathname === "/admin/sources") { initAdmin(api); return true; }
  return false;
}

function initDebug(api) {
  layout("Diagnóstico de providers", `<p>As fontes mostradas como reproduzíveis foram verificadas pelo backend.</p><label>Chave administrativa <input id="admin-key" type="password" value="${escapeHTML(sessionStorage.getItem("craftplay_admin_key") || "")}"></label>
    <form id="debug-form" class="diagnostic-form"><input name="title" placeholder="Título" required><select name="media_type"><option value="movie">Filme</option><option value="series">Série</option><option value="anime">Anime</option><option value="cartoon">Desenho</option></select><input name="year" type="number" placeholder="Ano"><input name="season" type="number" min="0" placeholder="Temporada"><input name="episode" type="number" min="0" placeholder="Episódio"><button class="btn btn-primary">TESTAR PROVIDERS</button><button id="test-engines" type="button" class="btn btn-ghost">FONTES DE TESTE</button></form><div id="debug-results"></div><div id="test-player" class="diagnostic-player"></div>`);
  const key = () => { const value = document.querySelector("#admin-key").value; sessionStorage.setItem("craftplay_admin_key", value); return value; };
  const results = document.querySelector("#debug-results"), playerMount = document.querySelector("#test-player"); let controller;
  const renderSources = (sources) => { results.innerHTML = `<h2>Resultados</h2><ul class="source-results">${sources.map(sourceRow).join("")}</ul>${sources.some((item) => item.is_playable) ? `<select id="test-source">${sources.map((item, index) => `<option value="${index}" ${item.is_playable ? "" : "disabled"}>${escapeHTML(item.provider)} · ${item.type}</option>`).join("")}</select><button id="play-test" class="btn btn-primary">TESTAR PLAYER</button>` : ""}`; document.querySelector("#play-test")?.addEventListener("click", async () => { const source = sources[Number(document.querySelector("#test-source").value)]; controller ||= new PlayerController(playerMount); await controller.load(source); await controller.play(); }); };
  document.querySelector("#debug-form").addEventListener("submit", async (event) => { event.preventDefault(); results.textContent = "Testando providers..."; const data = Object.fromEntries(new FormData(event.target)); for (const field of ["year", "season", "episode"]) data[field] = data[field] ? Number(data[field]) : field === "year" ? null : 0; try { const response = await api.debugProviders(data, key()); const sources = response.providers.flatMap((provider) => provider.sources); results.innerHTML = response.providers.map((provider) => `<section><h3>${escapeHTML(provider.name)} · ${escapeHTML(provider.status)}</h3><p>${provider.candidates} candidato(s)</p><ul class="source-results">${provider.sources.map(sourceRow).join("")}</ul></section>`).join(""); if (sources.length) results.insertAdjacentHTML("beforeend", `<button id="use-results" class="btn btn-primary">TESTAR PRIMEIRA FONTE</button>`), document.querySelector("#use-results").onclick = async () => { controller ||= new PlayerController(playerMount); await controller.load(sources[0]); await controller.play(); }; } catch (error) { results.textContent = error.message; } });
  document.querySelector("#test-engines").onclick = async () => { results.textContent = "Validando MP4, HLS, DASH, YouTube e Vimeo..."; try { renderSources((await api.testSources(key())).sources); } catch (error) { results.textContent = error.message; } };
}

function initAdmin(api) {
  layout("Fontes personalizadas", `<p>Cadastre somente mídia sua, licenciada ou oficialmente autorizada.</p><label>Chave administrativa <input id="admin-key" type="password" value="${escapeHTML(sessionStorage.getItem("craftplay_admin_key") || "")}"></label>
    <form id="source-form" class="diagnostic-form"><input name="media_id" placeholder="tmdb:movie:123" required><select name="media_type"><option value="movie">Filme</option><option value="series">Série</option><option value="anime">Anime</option><option value="cartoon">Desenho</option></select><input name="provider" value="custom" placeholder="Provider"><input name="url" type="url" placeholder="https://..." required><select name="source_type"><option>mp4</option><option>hls</option><option>dash</option><option>embed</option><option>youtube</option><option>vimeo</option></select><input name="language" value="pt-BR"><input name="quality" value="auto"><input name="season" type="number" min="0" value="0"><input name="episode" type="number" min="0" value="0"><button class="btn btn-primary">VALIDAR E CADASTRAR</button></form><div id="admin-results"></div>`);
  const key = () => { const value = document.querySelector("#admin-key").value; sessionStorage.setItem("craftplay_admin_key", value); return value; }, target = document.querySelector("#admin-results");
  const load = async () => { try { const response = await api.customSources(key()); target.innerHTML = `<ul class="source-results">${response.items.map((item) => `<li><b>${escapeHTML(item.media_id)}</b> · ${escapeHTML(item.provider)} · ${escapeHTML(item.source_type)} · ${item.enabled ? "ativa" : "inativa"}<br><code>${escapeHTML(item.url)}</code><div><button class="btn btn-ghost toggle" data-id="${item.id}" data-enabled="${!item.enabled}">${item.enabled ? "Desativar" : "Ativar"}</button><button class="btn btn-ghost remove" data-id="${item.id}">Excluir</button></div></li>`).join("")}</ul>`; target.querySelectorAll(".toggle").forEach((button) => button.onclick = async () => { await api.toggleCustomSource(button.dataset.id, button.dataset.enabled, key()); load(); }); target.querySelectorAll(".remove").forEach((button) => button.onclick = async () => { if (confirm("Excluir esta fonte?")) { await api.deleteCustomSource(button.dataset.id, key()); load(); } }); } catch (error) { target.textContent = error.message; } };
  document.querySelector("#admin-key").addEventListener("change", load); document.querySelector("#source-form").onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); data.season = Number(data.season); data.episode = Number(data.episode); data.enabled = true; target.textContent = "Validando fonte..."; try { await api.addCustomSource(data, key()); await load(); } catch (error) { target.textContent = error.message; } }; if (document.querySelector("#admin-key").value) load();
}
